[logger]
level='info'

[client]
showErrorDetails='none'
toolbarMode='minimal'
showSidebarNavigation=false

[runner]
fastReruns=false

[server]
enableStaticServing=true

[browser]
gatherUsageStats=false

[theme]
base='dark'
primaryColor='rgb(62, 150, 170)'